### ISSUE TITLE
Vacuum cleaner card is not displayed in V1.11.0

### ISSUE THREAD

**Issue by CM000n** [denysdovhan/vacuum-card#125]
**Describe the bug**

Hi, I use this card in combination with PiotrMachowski's Xiaomi Cloud Extractor Custom Copmontent.: https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor
So far, the vacuum live map display has worked perfectly with this card. However, since I updated the vacuum cleaner card to V1.11.0 today, I can no longer see the vacuum cleaner live map in the frontend.

The Cloud Extractor components of Piotr have not changed in this time. And the map of it is correctly shown in the HA developer tools.

I have already tried to clear the browser cache and tried several devices. But it is no longer displayed anywhere.

Many thanks in advance and thanks in general for this great lovelace card

This is the part of my Lovelace code of the vacuum cleaner card:
```yml
  cards:
    - type: "custom:vacuum-card"
      style: |
        ha-card {
          box-shadow: none;
          color: white;
          --lovelace-background: white;
        }
      entity: vacuum.xiaomi_vacuum_cleaner
      show_name: false
      map: camera.robi_karte
      stats:
        default:
          - attribute: filter_left
            unit: Std.
            subtitle: Filter
          - attribute: side_brush_left
            unit: Std.
            subtitle: Seitenbürste
          - attribute: main_brush_left
            unit: Std.
            subtitle: Hauptbürste
          - attribute: sensor_dirty_left
            unit: Std.
            subtitle: Sensoren
        cleaning:
          - attribute: cleaned_area
            unit: m²
            subtitle: Reinigungsfläche
          - attribute: cleaning_time
            unit: Min.
            subtitle: Reinigungszeit
```

**Steps to reproduce**

1. Go to HACS
2. Update to Vacuum Cleaner Card V1.11.0
4. Vacuum cleaner card is not displayed anymore in Frontend

**Expected behavior**
The map should be displayed within the vacuum cleaner card

**Screenshots**

Frontend:
![frontend](https://user-images.githubusercontent.com/7945681/95336438-f99cc800-08b0-11eb-8f07-c33786440335.PNG)

Vacuum Map from Xiaomi-Cloud-Map-Extractor as shown in HA Developer Tools:
![backend](https://user-images.githubusercontent.com/7945681/95336561-1a651d80-08b1-11eb-8ecf-3390be8e1139.PNG)

**Versions:**

- Release: V1.11.0
- Browser: MS Edge 85.0.564.70 
- HomeAssistant version: 0.115.6
