### ISSUE TITLE
Start Clean from script, didn't change status from idle

### ISSUE THREAD

**Issue by Hama4tux** [denysdovhan/vacuum-card#146]
When i run cleaning by play button in Vacuum Card is state change , if i run clean from custom action in Vacuum Card state is still idle

Card Configuration:

```
        actions:
          - name: Clean Obyvák
            service: script.clean_obyvak
            icon: 'mdi:sofa'

```
Script configuration: 
```
clean_obyvak:
    sequence:
      - service: xiaomi_vacuum.vacuum_clean_zone
        data:
          entity_id: vacuum.alfred
          zone: '-2500,-10000,4200,-6000'
          repeats: 1     
```
![image](https://user-images.githubusercontent.com/74649596/99506611-9a87a400-2982-11eb-95bf-4e053a317ea5.png)
