### ISSUE TITLE
Card not refreshing

### ISSUE THREAD

**Issue by sheminasalam** [denysdovhan/vacuum-card#188]
I have the latest version of HA and this card. It is working fine except this issue. I have a input_text entity that is updated with the name of the room where the robovac is cleaning. i have used this entity as a stat while cleaning. The problem is that even after the state of this entity changes, the state in the card doesn't change. I have to refresh the entire page in browser to see the updated state. Why is it so? any advises?

**Comment by denysdovhan** [comment]
It might update with delays up to a minute, because of HA passing updated values to the card with delays.

Are you sure it doesn't update at all?

**Comment by sheminasalam** [comment]
No it doesn't change even after 1 minute. I just now checked. It change only after refreshing web webpage.
By the way is there a method to to show the stats in different lines rather than in one line?

**Comment by denysdovhan** [comment]
That's strange. Any tips on how to reproduce it?

>  is there a method to to show the stats in different lines rather than in one line?

No, there isn't.

**Comment by sheminasalam** [comment]
This is the config part of my card. This intput_text entity is updated with the name of the room that the robovac is cleaning. Thats all
```
  - type: 'custom:vacuum-card'
    entity: vacuum.robo_vacuum
    stats:
      cleaning:
        - entity: entity: input_text.robo_action
        - attribute: s_area
          unit: minutes
          subtitle: Cleaning time
        - attribute: s_time
          unit: minutes
          subtitle: Cleaning time
```
