### ISSUE TITLE
Resolve templates in actions

### ISSUE THREAD

**Issue by lcnittl** [denysdovhan/vacuum-card#224]
### Is your feature request related to a problem? Please describe.
[Ecovacs vacuum cleaners use attributes to link room names to room IDs](https://github.com/And3rsL/Deebot-for-Home-Assistant#templates). To have the card's actions automagically clean the correct room by room name, rather than room IDs, one – to my understanding – has to use a script that resolves the room name to room IDs via a template (cf. Describe alternatives you've considered – My Current Configuration).

### Describe the solution you'd like – Desired Configuration

I think it would be awesome if one could spare that script and dump all the info directly in the card's configuration?

That is per action:

```yaml
  - name: Clean bathroom
    service: vacuum.send_command
    service_data:
      entity_id: vacuum.MY_ROBOT
      command: spot_area
      params:
        rooms: '{{ state_attr("vacuum.MY_ROBOT", "room_bathroom") }}'  # Template to resolve room name
        cleanings: 1
    icon: mdi:hot-tub
```

The whole config would then look like this:

```yaml
type: custom:vacuum-card
entity: vacuum.MY_ROBOT
stats:
  default:
    - entity_id: sensor.MY_ROBOT_sidebrush
      unit: '%'
      subtitle: Side Brush
    - entity_id: sensor.MY_ROBOT_brush
      unit: '%'
      subtitle: Main Brush
    - entity_id: sensor.MY_ROBOT_heap
      unit: '%'
      subtitle: Filter
  cleaning:
    - entity_id: sensor.MY_ROBOT_stats_area
      unit: m2
      subtitle: Area
    - entity_id: sensor.MY_ROBOT_stats_time
      unit: min
      subtitle: Time
    - entity_id: binary_sensor.MY_ROBOT_mop_attached
      subtitle: Mop mode
actions:
  - name: Clean bathroom
    service: vacuum.send_command
    service_data:
      entity_id: vacuum.MY_ROBOT
      command: spot_area
      params:
        rooms: '{{ state_attr("vacuum.MY_ROBOT", "room_bathroom") }}'
        cleanings: 1
    icon: mdi:hot-tub
  - name: Clean bedroom
    service: vacuum.send_command
    service_data:
      entity_id: vacuum.MY_ROBOT
      command: spot_area
      params:
        rooms: '{{ state_attr("vacuum.MY_ROBOT", "room_bedroom") }}'
        cleanings: 1
    icon: mdi:bed-empty
  - name: Clean living room
    service: vacuum.send_command
    service_data:
      entity_id: vacuum.MY_ROBOT
      command: spot_area
      params:
        rooms: '{{ state_attr("vacuum.MY_ROBOT", "room_living_room") }}'
        cleanings: 1
    icon: mdi:sofa
  - name: Clean kitchen
    service: vacuum.send_command
    service_data:
      entity_id: vacuum.MY_ROBOT
      command: spot_area
      params:
        rooms: '{{ state_attr("vacuum.MY_ROBOT", "room_kitchen") }}'
        cleanings: 1
    icon: mdi:silverware-fork-knife
  - name: Clean kids room
    service: vacuum.send_command
    service_data:
      entity_id: vacuum.MY_ROBOT
      command: spot_area
      params:
        rooms: '{{ state_attr("vacuum.MY_ROBOT", "room_kids_room") }}'
        cleanings: 1
    icon: mdi:odnoklassniki
show_name: true
compact_view: false
map: camera.MY_ROBOT_livemap
```

### Describe alternatives you've considered – My Current Configuration

It works, of course, with a script that processes the template.

**Card Configuration**
```yaml
type: custom:vacuum-card
entity: vacuum.MY_ROBOT
stats:
  default:
    - entity_id: sensor.MY_ROBOT_sidebrush
      unit: '%'
      subtitle: Side Brush
    - entity_id: sensor.MY_ROBOT_brush
      unit: '%'
      subtitle: Main Brush
    - entity_id: sensor.MY_ROBOT_heap
      unit: '%'
      subtitle: Filter
  cleaning:
    - entity_id: sensor.MY_ROBOT_stats_area
      unit: m2
      subtitle: Area
    - entity_id: sensor.MY_ROBOT_stats_time
      unit: min
      subtitle: Time
    - entity_id: binary_sensor.MY_ROBOT_mop_attached
      subtitle: Mop mode
actions:
  - name: Clean bathroom
    service: script.MY_ROBOT_clean_room
    service_data:
        room: bathroom
    icon: mdi:hot-tub
  - name: Clean bedroom
    service: script.MY_ROBOT_clean_room
    service_data:
        room: bedroom
    icon: mdi:bed-empty
  - name: Clean living room
    service: script.MY_ROBOT_clean_room
    service_data:
        room: living_room
    icon: mdi:sofa
  - name: Clean kitchen
    service: script.MY_ROBOT_clean_room
    service_data:
        room: kitchen
    icon: mdi:silverware-fork-knife
  - name: Clean kids room
    service: script.MY_ROBOT_clean_room
    service_data:
        room: kids_room
    icon: mdi:odnoklassniki
show_name: true
compact_view: false
map: camera.MY_ROBOT_livemap
```

**script.MY_ROBOT_clean_room**
```yaml
alias: MY_ROBOT_clean_room
sequence:
  - service: vacuum.send_command
    target:
      entity_id: vacuum.MY_ROBOT
    data:
      command: spot_area
      params:
        rooms: '{{ state_attr("vacuum.MY_ROBOT", "room_" + room) }}'
        cleanings: 1
mode: single
```

### Additional context

Quite new to Home Assistant and unfortunately not sure if template resolution is possible in such a context. And I agree that it is – in this case – quite a duplication of config parameters (`entity_id`, `command`, `cleanings`).
