### ISSUE TITLE
Allow state dependent icons for actions

### ISSUE THREAD

**Issue by lanrat** [denysdovhan/vacuum-card#249]
**Is your feature request related to a problem? Please describe.**

I have an action defined to toggle an automation that automatically starts/stops my vacuum on a schedule.

There is currently no way to determine if the automation is enabled/disabled in this card UI.

Action code:

```yaml
actions:
  - name: Auto Clean
    service: automation.toggle
    icon: hass:robot
    service_data:
      entity_id: automation.clean_schedule
```

**Describe the solution you'd like**

It would be nice if the `actions` section could be expanded to show a different icon (or color) depending on a state. This would be inline with the rest of the Home Assistant UI where the off state is blue and on is yellow (in the default theme).

This might also be achievable by implementing #248 and using templates to change the icon color.

**Describe alternatives you've considered**

Adding another card to display the automation status.

**Additional context**

<img width="465" alt="Screen Shot 2021-08-02 at 2 43 21 PM" src="https://user-images.githubusercontent.com/164192/127927611-d847c8b8-2cf7-4485-a580-7b02d5354ae3.png">
