### ISSUE TITLE
entity states do not update

### ISSUE THREAD

**Issue by lanrat** [denysdovhan/vacuum-card#250]
**Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Describe the bug**

When defining `stats` that use an `entity_id` that is not the main vacuum entity, when their state changes, it is not reflected in the UI unless the page is manually reloaded.

**Steps to reproduce**

1. Create a card with the yaml config below. Replace `automation.clean_when_away` with any binary state that is not part of the main vacuum entity.
2. Toggle the binary state of the entity you selected. It will not be updated in the card UI
3. Refresh the page. The card UI is updates.

```yaml
type: custom:vacuum-card
entity: vacuum.roomba
image: default
stats:
  default:
    - attribute: bin_full
      subtitle: Bin Full
    - entity_id: automation.clean_when_away
      subtitle: Auto Clean
compact_view: true
show_name: true
show_status: true
show_toolbar: true
```

**Expected behavior**
When the entity state is changed, the new state value should be automatically reflected in the UI.

**Versions:**

- Release: v1.23.0
- Browser: Chrome
- HomeAssistant version: 2021.7.4

**Comment by igorsantos07** [comment]
Additionally, is it possible to show an attribute from a different entity? I thought I could do it by using `entity_id`+`attribute`, but on a second read I guess `entity_id` only shows the state? Should I open a feature request about this, or is it just a bug?

-----------
_Previous text:_

In my case, I'm trying to create a frankenstein-card with two different integrations - miio2 is faster and has more commands, but viomi has stats. I tried adding the stats with `entity_id` but they actually just show the entity state, not the given attribute:

```yaml
[...]

entity: vacuum.miio2
stats:
  default:
    - attribute: main_brush_left
      entity_id: vacuum.viomi_vacuum_v7
      unit: h
      subtitle: Main brush
```
