### ISSUE TITLE
2021.11 will break card?

### ISSUE THREAD

**Issue by andriej** [denysdovhan/vacuum-card#275]
There is breaking change mentioned in 2021.11 rc release note:
https://rc--home-assistant-docs.netlify.app/blog/2021/10/27/release-202111/

> Attributes from the vacuum entities have been replaced with sensors.
> 
> This means that all your references to these attributes must be replaced with its sensor in your automations, scripts and dashboards.
> 
> Some sensors have been disabled by default and need manual enablement, once the integration has been set up. For example, the attribute mop_attached: true has now been replaced with binary_sensor.<NAME>_mop_attached.

I assume it may break card.

**Comment by jscherry** [comment]
Same problem after installing 2021.11 beta versions.

**Comment by TheFes** [comment]
It does indeed break the card. No information about brushes available anymore.

**Comment by ardeus-ua** [comment]
In 2021.11 it will be presented as diagnostic sensors which you will need to activate in device settings through the integrations but time will show up in seconds

**Comment by andriej** [comment]
Yes, but card won't show those sensors right away

**Comment by Drafteed** [comment]
Icons disappeared after the update on 2021.11.0:

<img src="https://user-images.githubusercontent.com/11841379/140199360-ac9ec597-2438-4d50-bba7-cf549426a392.png" width="300">

[mini-media-player fixed it in the following way](https://github.com/kalkih/mini-media-player/pull/556/commits/63c73b5b9aab3132e91dd79e87fd8d44030aed0c).

**Comment by Xitro01** [comment]
> Icons disappeared after the update on 2021.11.0:
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/11841379/140199360-ac9ec597-2438-4d50-bba7-cf549426a392.png">
> 
> [mini-media-player fixed it in the following way](https://github.com/kalkih/mini-media-player/pull/556/commits/63c73b5b9aab3132e91dd79e87fd8d44030aed0c).

Yup, icons are broken. Hopefully a quick fix will follow!

**Comment by mortenmoulder** [comment]
Confirmed - the card is broken.

**Comment by OliverSkivdal** [comment]
For anyone looking for a quickfix:

You will need to add template sensors for each state, example:
```
- platform: template
  sensors:
    vacuum_card_filter:
      value_template: "{{ ((states.sensor.vacuum_filter_left.state | float / 600)) | round(0) }}"
      unit_of_measurement: "hours"
```

Then add those sensors to the card to display stats correctly:
```
stats:
  default:
    - entity_id: sensor.vacuum_card_filter
      unit: hours
      subtitle: Filter
    - entity_id: sensor.vacuum_card_side_brush
      unit: hours
      subtitle: Sidebørste
    - entity_id: sensor.vacuum_card_main_brush
      unit: hours
      subtitle: Hovedbørste
    - entity_id: sensor.vacuum_card_sensors
      unit: hours
      subtitle: Sensorer
```

To get the buttons on the bottom of the card visible again, I used the custom card-mod component from HACS, (this fixed it for me in Firefox and on the Android app, but not in Chrome on desktop):
```
style: |
  .toolbar {
    background: transparent !important;
    min-height: 30px;
    display: flex;
    flex-direction: row;
    flex-flow: row wrap;
        flex-wrap: wrap;
    flex-wrap: wrap;
    justify-content: space-evenly;
  }
```
