### ISSUE TITLE
Vacuum attributes are now sensors (entities) since last Xiaomi integration Update

### ISSUE THREAD

**Issue by Djal94** [denysdovhan/vacuum-card#279]
Hello,

Since last Xiaomi integration Update, all the old  vacuum « attributes » are now sensors/entities, so they’re not showing in the card.
![744D82F9-5D7B-47DB-9C24-A540F546B622](https://user-images.githubusercontent.com/35771339/140590708-01174f22-0843-4c3a-8ceb-91eba9d1580c.png)
![37E9867A-88DF-40B6-A2A2-9A32AF4D314F](https://user-images.githubusercontent.com/35771339/140590748-33e8e68a-06b5-4fdd-9381-52e74a6e5eda.jpeg)

**Comment by mmegaromm** [comment]
Yes, it became not convenient if you add via
```
type: vertical-stack
cards:
  - type: custom:vacuum-card
    entity: vacuum.roborock_vacuum_s5e
    stats:
      default:
        - entity_id: sensor.roborock_vacuum_s5e_last_clean_duration
          unit: сек
          subtitle: Время уборки
        - entity_id: sensor.roborock_vacuum_s5e_last_clean_area
          unit: кв м
          subtitle: Площадь уборки
        - entity_id: sensor.roborock_vacuum_s5e_main_brush_left
          unit: ч
          subtitle: Фильтр(150ч)
        - entity_id: sensor.roborock_vacuum_s5e_side_brush_left
          unit: ч
          subtitle: Щетка(300ч)
    actions:
      - name: Душевая
        service: script.1631693539423
        icon: mdi:shower
      - name: Никита
        service: script.1631693839750
        icon: mdi:bed-empty
    image: default
    compact_view: false
    show_toolbar: true
    show_status: true
```

Now we need to create each parameter 1 more sensor with the value rounded
or converting seconds into minutes and so on

**Comment by tzagim** [comment]
See https://github.com/denysdovhan/vacuum-card/issues/275#issuecomment-960528491

**Comment by kimme1024** [comment]
issue here is that the sensordata doesn't really make sense.
there's an "s" at the end of it but it isn't seconds when I compare it to the data in the app.

ex: 
main brush sensor data: 1.768s (29ish minutes)
main brush app data: 288h left

**Comment by Djal94** [comment]
> issue here is that the sensordata doesn't really make sense.
> 
> there's an "s" at the end of it but it isn't seconds when I compare it to the data in the app.
> 
> 
> 
> ex: 
> 
> main brush sensor data: 1.768s (29ish minutes)
> 
> main brush app data: 288h left

It's good for me.

**Comment by denysdovhan** [comment]
This is not something that can be resolved on the vacuum-card side. That's because HA broke the way vacuum params are represented.

**Comment by PiotrMachowski** [comment]
@denysdovhan actually it can, but you have to make a few calls to WS API

**Comment by balbulator** [comment]
But I don't have objects like brush, filter, etc. How do I create them?

**Comment by ProjektBisarr** [comment]
> But I don't have objects like brush, filter, etc. How do I create them?

You have to enable them first. Go to xiaomi integration, click on entities and enable the ones you need to use.

**Comment by balbulator** [comment]
> > But I don't have objects like brush, filter, etc. How do I create them?
> 
> You have to enable them first. Go to xiaomi integration, click on entities and enable the ones you need to use.

Objects have nothing to click

**Comment by PiotrMachowski** [comment]
@denysdovhan [here](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card/blob/master/src/utils.ts#L154) you can check how I have retrieved data from sensors

**Comment by szafran81** [comment]
Hi,

Does anyone have problems with visibility of the cleaning stats?
I can see the default stats on the card, but the cleaning stats are invisible.

![image](https://user-images.githubusercontent.com/2608332/143188317-f718d42e-0a7d-4ad3-bb1b-7f667ebeb598.png)

```
stats:
  default:
    - entity_id: sensor.main_filter
      unit: min
      subtitle: Filtr
    - entity_id: sensor.right_brush
      unit: min
      subtitle: Szczotka boczna
    - entity_id: sensor.main_brush
      unit: min
      subtitle: Szczotka główna
    - entity_id: sensor.sensor_cleaning
      unit: min
      subtitle: Czujniki
  cleaning:
    - entity_id: sensor.current_statistics_area
      unit: m2
      subtitle: Powierzchnia
    - entity_id: sensor.current_statistics_time
      unit: minutes
      subtitle: Czas
```

Any ideas ?

**Comment by denysdovhan** [comment]
This cannot be resolved in vacuum-card, because we want to keep `stats` section as general as possible. HA changed data representation for Xiaomi vacuums. Here's how I resolved the issue for myself via template sensors:

```yaml
  # Vacuum
  - platform: template
    sensors:
      roborock_main_brush_left_hours:
        value_template: >-
          {{ (states('sensor.roborock_main_brush_left') | float / 3600) | round(1) }}
      roborock_side_brush_left_hours:
        value_template: >-
          {{ (states('sensor.roborock_side_brush_left') | float / 3600) | round(1) }}
      roborock_filter_left_hours:
        value_template: >-
          {{ (states('sensor.roborock_filter_left') | float / 3600) | round(1) }}
      roborock_sensor_dirty_left_hours:
        value_template: >-
          {{ (states('sensor.roborock_sensor_dirty_left') | float / 3600) | round(1) }}
```

Ref: https://github.com/denysdovhan/smart-home/blob/master/home-assistant/integrations/sensor.yaml#L144-L161
