### ISSUE TITLE
Control buttons are not visible after upgrading to 2.2.2 version

### ISSUE THREAD

**Issue by ihor-chaban** [denysdovhan/vacuum-card#289]
Control buttons on the bottom panel are not visible after upgrading to 2.2.2 version.
They are not visible but they are there and clickable, when I hover the cursor I see the circle and the button name, but still not visible.
![screenshot_11-11-21_15-54-51](https://user-images.githubusercontent.com/25959371/141310496-960552da-28e2-4232-8fdd-541ac9341165.png)

**upd.** Looks like something related to material icons.

**Comment by Alxspb** [comment]
+1

**Comment by ihor-chaban** [comment]
Upgraded Home Assistant to the latest version also and it fixed the issue.

**Comment by TomHejret** [comment]
Upgrade to latest HA (Home Assistant 2021.11.3 running in Docker) didn't work for me :(
```
type: custom:vacuum-card
entity: vacuum.bob
image: default
stats:
  default:
    - attribute: filter_left
      unit: h
      subtitle: Filter
    - attribute: side_brush_left
      unit: h
      subtitle: Side brush
    - attribute: main_brush_left
      unit: h
      subtitle: Main brush
    - attribute: sensor_dirty_left
      unit: h
      subtitle: Sensors
    - attribute: cleaned_area
      unit: m2
      subtitle: Cleaned area
    - attribute: cleaning_time
      unit: min
      subtitle: Cleaning time
  cleaning:
    - attribute: cleaned_area
      unit: m2
      subtitle: Cleaning area
    - attribute: cleaning_time
      unit: min
      subtitle: Cleaning time
actions:
  - name: Ukliď celý byt (a resetuj počítadlo)
    service: script.start_cleaning_and_reset_counter
    icon: mdi:home-floor-0
  - name: Ukliď ložnici
    service: script.start_bedroom_cleaning
    icon: mdi:bed-empty
  - name: Ukliď pracovnu
    service: script.start_workroom_cleaning
    icon: mdi:laptop
  - name: Ukliď na toaletě
    service: script.start_toilet_cleaning
    icon: mdi:toilet
  - name: Přijeď ke koši
    service: script.send_vacuum_to_bin
    icon: mdi:trash-can-outline
compact_view: false
show_name: true
show_status: true
show_toolbar: true
```
![image](https://user-images.githubusercontent.com/28923134/141489585-ed0d4918-c975-44b8-b30b-0788c0260aa9.png)
There should be more buttons (also several custom) and also stat values does not show up (they were put aside of main entity in Novermber HA release).
![image](https://user-images.githubusercontent.com/28923134/141489872-6f886e0f-48c2-4ae6-946f-3847a4345e39.png)

It is Xiaomi Roborock S5 Max.

**Comment by balbulator** [comment]
> Upgrade to latest HA (Home Assistant 2021.11.3 running in Docker) didn't work for me :(
> 
> ```
> type: custom:vacuum-card
> entity: vacuum.bob
> image: default
> stats:
>   default:
>     - attribute: filter_left
>       unit: h
>       subtitle: Filter
>     - attribute: side_brush_left
>       unit: h
>       subtitle: Side brush
>     - attribute: main_brush_left
>       unit: h
>       subtitle: Main brush
>     - attribute: sensor_dirty_left
>       unit: h
>       subtitle: Sensors
>     - attribute: cleaned_area
>       unit: m2
>       subtitle: Cleaned area
>     - attribute: cleaning_time
>       unit: min
>       subtitle: Cleaning time
>   cleaning:
>     - attribute: cleaned_area
>       unit: m2
>       subtitle: Cleaning area
>     - attribute: cleaning_time
>       unit: min
>       subtitle: Cleaning time
> actions:
>   - name: Ukliď celý byt (a resetuj počítadlo)
>     service: script.start_cleaning_and_reset_counter
>     icon: mdi:home-floor-0
>   - name: Ukliď ložnici
>     service: script.start_bedroom_cleaning
>     icon: mdi:bed-empty
>   - name: Ukliď pracovnu
>     service: script.start_workroom_cleaning
>     icon: mdi:laptop
>   - name: Ukliď na toaletě
>     service: script.start_toilet_cleaning
>     icon: mdi:toilet
>   - name: Přijeď ke koši
>     service: script.send_vacuum_to_bin
>     icon: mdi:trash-can-outline
> compact_view: false
> show_name: true
> show_status: true
> show_toolbar: true
> ```
> 
> ![image](https://user-images.githubusercontent.com/28923134/141489585-ed0d4918-c975-44b8-b30b-0788c0260aa9.png) There should be more buttons (also several custom) and also stat values does not show up (they were put aside of main entity in Novermber HA release). ![image](https://user-images.githubusercontent.com/28923134/141489872-6f886e0f-48c2-4ae6-946f-3847a4345e39.png)
> 
> It is Xiaomi Roborock S5 Max.

Settings -> Integrations -> Xiaomi Miio -> Vacuum Bob -> objects -> Activate object

**Comment by balbulator** [comment]
```
actions:
  - name: Ukliď celý byt (a resetuj počítadlo)
    service: script.start_cleaning_and_reset_counter
    icon: mdi:home-floor-0
  - name: Ukliď ložnici
    service: script.start_bedroom_cleaning
    icon: mdi:bed-empty
  - name: Ukliď pracovnu
    service: script.start_workroom_cleaning
    icon: mdi:laptop
  - name: Ukliď na toaletě
    service: script.start_toilet_cleaning
    icon: mdi:toilet
  - name: Přijeď ke koši
    service: script.send_vacuum_to_bin
    icon: mdi:trash-can-outline
```
**action:** replaced by **shortcuts:**

**Comment by raptr55** [comment]
> > It is Xiaomi Roborock S5 Max.
> 
> Settings -> Integrations -> Xiaomi Miio -> Vacuum Bob -> **objects** -> Activate object

Hi! I cant find the object section... Could you please take a screenshot?

**Comment by balbulator** [comment]
> > > It is Xiaomi Roborock S5 Max.
> > 
> > 
> > Settings -> Integrations -> Xiaomi Miio -> Vacuum Bob -> **objects** -> Activate object
> 
> Hi! I cant find the object section... Could you please take a screenshot?
![1](https://user-images.githubusercontent.com/61936199/141687518-69cf063f-2ed8-4e4d-9de9-c20124422f76.jpg)
![2](https://user-images.githubusercontent.com/61936199/141687533-1309d613-53ac-4a00-bd7e-0c45a32a3a47.jpg)
![3](https://user-images.githubusercontent.com/61936199/141687538-ffbc0b48-89ad-4b9b-85f8-81f37974df6f.jpg)
![4](https://user-images.githubusercontent.com/61936199/141687555-be610b73-5a00-4899-88f6-22a5c6300cb9.jpg)
![5](https://user-images.githubusercontent.com/61936199/141687560-67c7db16-3bd5-4a93-b2e3-0e20e80d0524.jpg)
![6](https://user-images.githubusercontent.com/61936199/141687565-94dc7176-46d1-4ad1-a1ad-7a2e79287b11.jpg)

**Comment by TomHejret** [comment]
Thanks, that was disabled indeed. Although enabling didn't solve the issue, even after HA restart.

**Comment by balbulator** [comment]
> Thanks, that was disabled indeed. Although enabling didn't solve the issue, even after HA restart.

```
      - type: 'custom:vacuum-card'
        compact_view: false
        entity: vacuum.xiaomi_vacuum_cleaner
        # map: camera.xiaomi_vacuum_map
        show_status: true
        show_toolbar: true
        stats:
          default:
            - entity_id: sensor.vacuum_filter_left
              unit: ч
              subtitle: Фильтр

            - entity_id: sensor.vacuum_side_brush_left
              unit: ч
              subtitle: Боковая щетка

            - entity_id: sensor.vacuum_main_brush_left
              unit: ч
              subtitle: Основная щетка

            - entity_id: sensor.vacuum_sensor_dirty_left
              unit: ч
              subtitle: Датчики

          cleaning:
            - entity_id: sensor.vacuum_cleaned_area
              unit: м²
              subtitle: Площадь уборки

            - entity_id: sensor.vacuum_cleaning_time
              unit: мин
              subtitle: Время уборки

        shortcuts:
          - name: Уборка гостиной
            service: script.clean_living_room
            icon: 'mdi:sofa'
          - name: Уборка спальни
            service: script.clean_bedroom
            icon: 'mdi:bed-empty'
          - name: Уборка кухни
            service: script.clean_kitchen
            icon: 'mdi:silverware-fork-knife'
          - name: Уборка прихожей
            service: script.clean_hallway
            icon: 'mdi:wardrobe'
```
Overwrite the code in Lovelace
