### ISSUE TITLE
Buttons are not displayed

### ISSUE THREAD

**Issue by Klabost** [denysdovhan/vacuum-card#296]
The buttons at the bottom of the card are not being displayed anymore since version >2.0. before hand i did not have any troubles.
I can hover over them and see that they are still there only their mdi:icon is not being displayed anymore.
The mdi icons are being displayed in other places in homeassistant. I also have this behavior with firefox, chrome and the homeassistant app.

**Comment by dersher** [comment]
I'm having this same issue.

**Comment by E-Sergey** [comment]
Hi! I have the same problem with shortcuts.

**Comment by Tomasinjo** [comment]
I don't think this is issue with version 2 since I was using v. 1.7.x and buttons disappeared after 2021.10 or 2021.11 update.

**Comment by itzyoungen** [comment]
Same issue here

**Comment by andrzejrostkowski** [comment]
Same here. 
HA: core-2021.11.5
vacuum-card: 2.2.3
I've also noticed, as Tomasinjo, that the problem probably appeared after HA update. I updated vacuum-card hoping it will resolve the issue, but no luck.

**Comment by kdelios** [comment]
Same here. But when my roborock is cleaning, they are visible.

**Comment by maxoss** [comment]
I'm still on 2021.10.6, same issue

**Comment by Furegato** [comment]
I'm on 2021.09.6 yet, and the bottom toolbar icons are not visible as well.

**Comment by Kseii** [comment]
Perhaps you have the buttons configured in the `actions` section of the configuration? If so, try moving them to `shortcuts`. This helped in my case, though I don't know the exact cause of this behavior.

i.e. use this:
```
actions:
  - icon: mdi:sofa
    name: Clean living room
    service: script.clean_living_room
```
instead of this:
```
shortcuts:
  - icon: mdi:sofa
    name: Clean living room
    service: script.clean_living_room
```

**Comment by T0ytoy** [comment]
@Kseii if I use `shortcuts`, nothing appears at all in the toolbar, except for the "play" button (still no icon on this one). With `actions`, at list I can press my invisibles buttons to exectutes scripts.

`type: custom:vacuum-card
entity: vacuum.vaisseau_mere_litter_box
image: https://brands.home-assistant.io/litterrobot/icon@2x.png
compact_view: false
show_name: true
show_status: true
show_toolbar: true
stats:
  default:
    - entity_id: sensor.vaisseau_mere_waste_drawer
      subtitle: Remplissage Bac
      unit: '%'
    - attribute: sleep_mode_enabled
      subtitle: Mode Silencieux Actif
    - attribute: clean_cycle_wait_time_minutes
      unit: minutes
      subtitle: Délai nettoyage
actions:
  - name: Remise à zéro du niveau du bac
    service: litterrobot.reset_waste_drawer
    icon: mdi:restart
    service_data:
      entity_id: vacuum.vaisseau_mere_litter_box
  - name: Activer / Désactiver Mode Silencieux
    service: script.toggle_litter_tray_sleep_mode
    icon: hass:sleep
  - name: Durée temporisation nettoyage
    service: script.update_litter_tray_cleaning_wait_time
    icon: hass:timer-sand
`

![image](https://user-images.githubusercontent.com/18136751/144850467-90c12492-cb4a-40a8-9dbb-daa16a53f3c3.png)
Here you can see on the bottom right, the highlighted button without icon.

**Comment by denysdovhan** [comment]
You should read changelog more carefully before updating. There was a breaking change in 2.0: `actions` are renamed to `shortcuts`.

**Comment by maxoss** [comment]
@denysdovhan and what about buttons which are not visible anymore? See picture above. 

Start, location and shortcuts icon are not showing. So there is still a bug

**Comment by 0neel** [comment]
@denysdovhan the issue is not related to actions-to-shortcuts change. I have the following config:
<details>
  <summary>Config</summary>
  
```yaml
  - type: custom:vacuum-card
    entity: vacuum.vacuum_cleaner
    image: default
    map: camera.xiaomi_cloud_map_extractor
    compact_view: false
    show_toolbar: true
    show_status: true
    show_name: false
    shortcuts:
    - name: Reload scripts
      icon: 'mdi:restart'
      service: script.reload
    stats:
      default:
      - attribute: filter_left
        unit: hours
        subtitle: Filter
      - attribute: side_brush_left
        unit: hours
        subtitle: Side brush
      - attribute: main_brush_left
        unit: hours
        subtitle: Main brush
      - attribute: sensor_dirty_left
        unit: hours
        subtitle: Sensors
```
</details>

And the shortcut is actually added to the card, but the icon for it is not visible - only the light blue background color is visible. The same for start and locate buttons on the left of the toolbar.
<img width="539" alt="Screenshot 2021-12-07 at 16 54 25" src="https://user-images.githubusercontent.com/3177746/145041773-fda79cd1-4e9b-4813-bcd8-cd4cf9aa6f91.png">
<img width="185" alt="Screenshot 2021-12-07 at 16 54 41" src="https://user-images.githubusercontent.com/3177746/145041853-1e65ea69-ffde-4953-bec5-f7e542ce55d7.png">
<img width="225" alt="Screenshot 2021-12-07 at 16 54 44" src="https://user-images.githubusercontent.com/3177746/145041860-7a0c8ac2-f062-4ca0-acae-4eda7f03d797.png">
