### ISSUE TITLE
boolean attributes no longer display when false

### ISSUE THREAD

**Issue by lanrat** [denysdovhan/vacuum-card#373]
**Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Describe the bug**

The latest version of tis card breaks the ability to display boolean `false` attributes in the stats section.

If the attribute value is `true` then it is displayed. If it is `false` then nothing is shown.

**Steps to reproduce**

card config:

```yaml
type: custom:vacuum-card
entity: vacuum.roomba
image: default
stats:
  default:
    - attribute: bin_full
      subtitle: Full
    - attribute: bin_present
      subtitle: Bin Present
  cleaning:
    - attribute: cleaned_area
      unit: m2
      subtitle: Cleaning area
    - attribute: cleaning_time
      unit: minutes
      subtitle: Cleaning time
compact_view: true
show_name: true
show_status: true
show_toolbar: true
actions:
  - name: Return To Base
    service: vacuum.return_to_base
    icon: mdi:home-map-marker
    service_data:
      entity_id: vacuum.roomba
```

Screenshot with `bin_present: true` and `bin_full: false`:
<img width="481" alt="Screen Shot 2022-04-26 at 11 32 14 AM" src="https://user-images.githubusercontent.com/164192/165368369-f9a32a3a-693f-4910-b958-e8568c033043.png">

I also tried using the new `value_template` and got the same results.

**Expected behavior**

For boolean attributes ti display `false` when they are false instead of nothing.

**Screenshots**

See above.

**Versions:**

- Release: 2.6.1
- Browser: chrome
- HomeAssistant version: 2022.4
