### ISSUE TITLE
value_template in stats is buggy

### ISSUE THREAD

**Issue by emufan** [denysdovhan/vacuum-card#378]
**Before submitting a bug**

[x ] I updated to the latest version available
[x ] I cleared the cache of my browser

**Describe the bug**

If I use value template for info data, something is wrong within the card.

**Steps to reproduce**

```
stats:
  default:
    - entity_id: sensor.mahroboter_messerqualitat
      value_template: '{{ "{0:_.0f}".format(1230) }}'
      unit: '%'
      subtitle: without replace
    - entity_id: sensor.mahroboter_messerqualitat
      value_template: '{{ "{0:_.0f}".format(1230).replace("_",".") }}'
      unit: '%'
      subtitle: with replace
```

so entity does not matter.

Result

![image](https://user-images.githubusercontent.com/22775515/165774748-bfbad3e8-1c16-4d06-b02c-cf70f33404b0.png)

This is (currently) only happending, if last digit is 0, compare to this

![image](https://user-images.githubusercontent.com/22775515/165774911-ee47f837-5f5d-4a2f-a8e4-46c7b1d607e3.png)
