### ISSUE TITLE
allow tap &hold actions 

### ISSUE THREAD

**Issue by qvqn** [denysdovhan/vacuum-card#413]
**Is your feature request related to a problem? Please describe.**
when pressing on the stats entity it only brings up more info, allowing to call services makes it simpler to reset counters from the card

**Describe the solution you'd like**
allow additional actions for stats entities

**Describe alternatives you've considered**
i was able to do this with a picture element card but was unable to do it with vacuum-card

**Additional context**
heres a config example from picture element

```
stats:
  default:
    - entity_id: sensor.vacuum_sensordirtyleft
      unit: hours
      subtitle: Sensors
      tap_action:
        action: more-info
      hold_action:
        action: call-service
        confirmation:
          text: Reset sensor?
        service: vacuum.send_command
        service_data:
          entity_id: vacuum.living
          command: reset_consumable
          params:
            - sensor_dirty_time
```
