### ISSUE TITLE
Mellerware City Move

### ISSUE THREAD

**Issue by antonio1475** [denysdovhan/vacuum-card#464]
Just dropping a thanks for this card, which is has allowed me to config a vacuum that is not natively/directly supported by HA or localtuya: Mellerware City Move. Thanks to localtuya and this card, I can have it in HA.

It's all explained in https://github.com/rospogrigio/localtuya/issues/1100

![image](https://user-images.githubusercontent.com/63130724/198044994-10bc60c4-6000-4b93-8bca-d219f75e9278.png)
![image](https://user-images.githubusercontent.com/63130724/198045022-68a9a26e-833c-40af-8d45-665e7e22e792.png)

I don't expect native support for this one, nor is it really needed with this config (explained in the ticket above, but here's the card code):
```
type: custom:vacuum-card
entity: vacuum.mellerware_city_move_vacuum
image: default
compact_view: false
show_name: true
show_status: true
show_toolbar: true
actions:
  start:
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 102
      value: clean_auto
  pause:
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 1
      value: pause
  stop:
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 1
      value: stop
  locate:
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 116
      value: true
  return_to_base:
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 102
      value: find_sta
stats:
  cleaning:
    - value_template: >-
        {{ (states.vacuum.mellerware_city_move_vacuum.attributes.clean_area |
        float(0) / 10) | round(1) }}
      unit: m²
      subtitle: Cleaned area
    - attribute: clean_time
      unit: minutes
      subtitle: Cleaning time
    - subtitle: Mode
      value_template: >-
        {% set mode =
        states.vacuum.mellerware_city_move_vacuum.attributes.cleaning_mode %} {%
        if mode == 'clean_auto' %} Auto {% elif mode == 'clean_random' %} Random
        {% elif mode == 'clean_wall' %} Wall {% elif mode == 'clean_spot' %}
        Spot {% else %} ' ' {% endif %}
shortcuts:
  - name: Auto
    icon: mdi:refresh-auto
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 102
      value: clean_auto
  - name: Random
    icon: mdi:arrow-all
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 102
      value: clean_random
  - name: Edge
    icon: mdi:border-radius
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 102
      value: clean_wall
  - name: Spot
    icon: mdi:target
    service: localtuya.set_dp
    service_data:
      device_id: bf4ac5c80b11f315d54w8l
      dp: 102
      value: clean_spot
```

**Comment by antonio1475** [comment]
With https://github.com/make-all/tuya-local , native support is now included and works with a simpler card:

```
type: custom:vacuum-card
entity: vacuum.aspirador
show_status: true
show_toolbar: true
image: default
stats:
  cleaning:
    - entity_id: sensor.aspirador_clean_area
      value_template: >
        {% if value == 'unknown' %}0{% else%}{{value}}{% endif%}
      unit: m²
      subtitle: Cleaned area
    - entity_id: sensor.aspirador_clean_time
      value_template: >
        {% if value == 'unknown' %}0{% else%}{{value}}{% endif%}
      unit: minutes
      subtitle: Cleaning time
    - subtitle: Mode
      entity_id: select.aspirador_clean_mode
      value_template: >
        {% if is_state('select.aspirador_clean_mode', 'unknown')  %}{{state_attr("vacuum.aspirador", "status") }}{% else%}{{states("select.aspirador_clean_mode") }}{% endif%}
```
