### ISSUE TITLE
DeeBot Vacuum is not showed in HA overview by vacuum-card.

### ISSUE THREAD

**Issue by tpbillund** [denysdovhan/vacuum-card#506]
I have added the HACS - Deebot 4 Home Assistant integration and have installed the HACS - Vacuum Card Frontend theme.
If im using this code, then nothing is showed on overview.
![Screenshot 2023-01-15 184904](https://user-images.githubusercontent.com/7550184/212744767-c17a2b6e-68fd-4b7e-ba8f-2da9f0bbbe6c.jpg)

```yaml
type: custom:vacuum-card
entity: vacuum.bertha
image: default
compact_view: false
show_name: true
show_toolbar: true
show_status: true
stats:
  default:
    - entity_id: sensor.bertha_life_span_side_brush
      unit: '%'
      subtitle: Side Brush
    - entity_id: sensor.bertha_life_span_brush
      unit: '%'
      subtitle: Main Brush
  cleaning:
    - entity_id: sensor.bertha_stats_area
      unit: m2
      subtitle: Area
    - entity_id: sensor.bertha_stats_time
      unit: min
      subtitle: Time
map: camera.bertha_live_map
```

If I then delete the default section, so I have this:
```yaml
type: custom:vacuum-card
entity: vacuum.bertha
image: default
compact_view: false
show_name: true
show_toolbar: true
show_status: true
stats:
  cleaning:
    - entity_id: sensor.bertha_stats_area
      unit: m2
      subtitle: Area
    - entity_id: sensor.bertha_stats_time
      unit: min
      subtitle: Time
map: camera.bertha_live_map
```

Then I get the Vacuum on the Overview.
![Screenshot 2023-01-15 184808](https://user-images.githubusercontent.com/7550184/212744835-c8305c46-f15d-48fb-b423-41b5aa441949.jpg)

But if I then start the Vacuum - it's gone again (no image) and I don't see a map over the cleaning.
![Screenshot 2023-01-15 184904](https://user-images.githubusercontent.com/7550184/212744866-6148cd17-eb35-4f17-879f-857cfacce2ce.jpg)

Can someone help me?

Additional information
Home Assistant 2023.1.4, Supervisor 2022.12.1, Operating System 9.4, Frontend 20230110.0 - latest
HACS Integration version: 1.29.1
Deebot 4 Home Assistant v1.5.0
Vacuum card v2.6.3
