### ISSUE TITLE
State attribute config does not work

### ISSUE THREAD

**Issue by berrywhite96** [denysdovhan/vacuum-card#522]
**Problem**
I am using in my config the `attribute` config in the `state` object. The card doesn't display any attribute I give it, instead it just shows the current entity status.

This is my config (shortened to the important part):
```
  - type: 'custom:vacuum-card'
    entity: vacuum.dreame_vacuum
    show_name: false
    stats:
        default:
        - entity_id: vacuum.dreame_vacuum
          attribute: main_brush_left
          subtitle: Hauptbürste
        - entity_id: vacuum.dreame_vacuum
          attribute: side_brush_left
          subtitle: Seitenbürste
        - entity_id: vacuum.dreame_vacuum
          attribute: filter_left
          subtitle: Filter
```

This config results to this card:
<img width="502" alt="Bildschirm­foto 2023-03-30 um 20 53 02" src="https://user-images.githubusercontent.com/24818127/228937132-c221a1be-3ce1-4f8a-8f0f-ab7d4a576d13.png">

This config just works like expected:
```
  - type: 'custom:vacuum-card'
    entity: vacuum.dreame_vacuum
    show_name: false
    stats:
        default:
        - value_template: "{{ state_attr('vacuum.dreame_vacuum', 'main_brush_left') }}%"
          subtitle: Hauptbürste
        - value_template: "{{ state_attr('vacuum.dreame_vacuum', 'side_brush_left') }}%"
          subtitle: Seitenbürste
        - value_template: "{{ state_attr('vacuum.dreame_vacuum', 'filter_left') }}%"
          subtitle: Filter
```

**Versions:**

- Release: v2.6.3
- Browser: Chrome 111.0.5563.110 (x86_64)
- HomeAssistant version: 2023.3.3
