### ISSUE TITLE
Unable to template value in stats-default section

### ISSUE THREAD

**Issue by bigboban** [denysdovhan/vacuum-card#545]
**Before submitting a bug**

[ x] I updated to the latest version available
[ x] I cleared the cache of my browser

**Describe the bug**

When i use "value_template" in stats-default section it does'n work as expected - nothing happens.

**Steps to reproduce**

```
stats:
  default:
    - entity_id: sensor.roborock_s7_cleaning_time
      unit: sekund
      subtitle: Poslední úklid trval
      value_template: '{{ (value | float(0) /60 | round(1) }}'

```

I think frontend ignores value_template because when i write anything in this line result is still the same - original value without any modification.

**Expected behavior**
value_template will modify value.

**Screenshots**
For example, JavaScript errors are shown in the web inspector (if applicable).

**Versions:**

- Release: 2.7.1
- Browser: Chrome
- HomeAssistant version: 2023.6.0
