### ISSUE TITLE
value template not used after values get updated

### ISSUE THREAD

**Issue by mindgam3s** [denysdovhan/vacuum-card#560]
**Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Describe the bug**

while the vacuum is running it updated values like 'current cleaning area' which gets updated in the custom:vacuum-card
BUT
it does not use the value template after an update and displays the plain data coming from the entity.

**Steps to reproduce**

1. Start Robot
2. track custom:vacuum-card data
3. See value-template not being applied

**Expected behavior**
Updated values appear by using the value template

**Real behavior**
Updated values appear unchanged

**Screenshots**

![vacuum_card_display_error](https://github.com/denysdovhan/vacuum-card/assets/34487011/0cce8241-60c1-447b-bfa3-056dbf59cecc)

**Versions:**

- Release: v2.7.3
- Browser: chrome
- HomeAssistant version:  2023.7.3

**Comment by mindgam3s** [comment]
custopm:vacuum-card config.yml
```
type: custom:vacuum-card
entity: vacuum.mr_kaplan
stats:
  default:
    - entity_id: sensor.mr_kaplan_verbleibende_sensorzeit
      value_template: ↓{{ (value | float(0) / 3600) | round(0) }}
      unit: Std.
      subtitle: Sensoren
    - entity_id: sensor.mr_kaplan_verbleibende_filterzeit
      value_template: ↓{{ (value | float(0) / 3600) | round(0) }}
      unit: Std.
      subtitle: Filter
    - entity_id: sensor.mr_kaplan_verbleibende_zeit_der_seitenburste
      value_template: ↓{{ (value | float(0) / 3600) | round(0) }}
      unit: Std.
      subtitle: Seitenbürste
    - entity_id: sensor.mr_kaplan_verbleibende_zeit_der_hauptburste
      value_template: ↓{{ (value | float(0) / 3600) | round(0) }}
      unit: Std.
      subtitle: Hauptbürste
  cleaning:
    - entity_id: sensor.mr_kaplan_reinigungszeit
      value_template: '{{ (value | float(0) / 60) | round(0) }}'
      unit: min
      subtitle: akt. Dauer ↑
    - entity_id: sensor.mr_kaplan_reinigungsbereich
      value_template: '{{ value }}'
      unit: m²
      subtitle: akt. Reinigungsbereich ↑
    - entity_id: sensor.mr_kaplan_gesamtreinigungszeit
      value_template: '{{ (value | float(0) / 3600) | round(0) }}'
      unit: Std.
      subtitle: Gesamtlaufzeit ↑
```

**Comment by ahuffman** [comment]
I am also seeing this behavior.  If you refresh the page the value templates are honored.  Additionally the switch from default state to cleaning works, however the stats do not update if the dashboard is left open until the state of the vacuum changes (i.e. the sensors are not continually polled/refreshed).

Here's my config for reference:

```yaml
type: custom:vacuum-card
entity: vacuum.huffbot
stats:
  default:
    - entity_id: sensor.huffbot_cycle_count
      subtitle: Cycles Completed
    - entity_id: sensor.huffbot_clean_mode
      subtitle: Mode
      value_template: |
        {% if value == "ultra" %}Ultra Clean{% endif %}
        {% if value == "short" %}Fast Mode{% endif %}
        {% if value == "floor" %}Floor Only{% endif %}
        {% if value == "water" %}Water Line{% endif %}
        {% if value == "all" %}Regular{% endif %}
        {% if value == "pickup" %}Pickup{% endif %}
    - entity_id: sensor.huffbot_status
      subtitle: Status
      value_template: |
        {% if value == "init" %}Initializing{% endif %}
        {% if value == "off" %}Off{% endif %}
        {% if value == "cleaning" %}Cleaning{% endif %}
  cleaning:
    - entity_id: sensor.huffbot_clean_mode
      subtitle: Mode
      value_template: |
        {% if value == "ultra" %}Ultra Clean{% endif %}
        {% if value == "short" %}Fast Mode{% endif %}
        {% if value == "floor" %}Floor Only{% endif %}
        {% if value == "water" %}Water Line{% endif %}
        {% if value == "all" %}Regular{% endif %}
        {% if value == "pickup" %}Pickup{% endif %}
    - entity_id: sensor.huffbot_cycle_time
      subtitle: Cycle
      value_template: '{{ value | float(0) / 60 }}'
      unit: Hour
    - entity_id: sensor.huffbot_cycle_time_left
      subtitle: Remaining
      value_template: '{{ ( value | float(0) / 60) | round }}'
      unit: Minutes
    - entity_id: select.huffbot_led_mode
      subtitle: LED Mode
      value_template: |
        {% if value == "1" %}Blinking{% endif %}
        {% if value == "2" %}Always On{% endif %}
        {% if value == "3" %}Disco{% endif %}
    - entity_id: number.huffbot_led_intensity
      subtitle: LED Intensity
      unit: '%'
image: /local/robot_icon_c.svg
show_status: false
show_name: true
```
