### ISSUE TITLE
[FEATURE]: Ability to disable/enable specific default buttons and fan speed display

### ISSUE THREAD

**Issue by ahuffman** [denysdovhan/vacuum-card#588]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to disable specific buttons such as 'dock' in the default display.

I'd also like to be able to control the display of the fan speed + select drop down with a value template or disable it all together.

Default:
![image](https://github.com/denysdovhan/vacuum-card/assets/4340269/5d1aad8a-ad01-48f2-b1f0-61c51e35b34b)

Cleaning:
![image](https://github.com/denysdovhan/vacuum-card/assets/4340269/6b5735cb-1382-4109-8284-2eaa66909904)

**Describe alternatives you've considered**
Just living with the non-prettified text and ignoring the dock button :).

**Additional context**
I'm using the Maytronics MyDolphin Plus integration (swimming pool vacuum) from HACS with this card.  Here is my code for reference:

```yaml
type: custom:vacuum-card
entity: vacuum.huffbot
stats:
  default:
    - entity_id: sensor.huffbot_cycle_count
      subtitle: Cycles Completed
    - entity_id: sensor.huffbot_clean_mode
      subtitle: Mode
      value_template: |
        {% if value == "ultra" %}Ultra Clean{% endif %}
        {% if value == "short" %}Fast Mode{% endif %}
        {% if value == "floor" %}Floor Only{% endif %}
        {% if value == "water" %}Water Line{% endif %}
        {% if value == "all" %}Regular{% endif %}
        {% if value == "pickup" %}Pickup{% endif %}
    - entity_id: sensor.huffbot_status
      subtitle: Status
      value_template: |
        {% if value == "init" %}Initializing{% endif %}
        {% if value == "off" %}Off{% endif %}
        {% if value == "cleaning" %}Cleaning{% endif %}
  cleaning:
    - entity_id: sensor.huffbot_clean_mode
      subtitle: Mode
      value_template: |
        {% if value == "ultra" %}Ultra Clean{% endif %}
        {% if value == "short" %}Fast Mode{% endif %}
        {% if value == "floor" %}Floor Only{% endif %}
        {% if value == "water" %}Water Line{% endif %}
        {% if value == "all" %}Regular{% endif %}
        {% if value == "pickup" %}Pickup{% endif %}
    - entity_id: sensor.huffbot_cycle_time
      subtitle: Cycle
      value_template: '{{ value | float(0) / 60 }}'
      unit: Hour
    - entity_id: sensor.huffbot_cycle_time_left
      subtitle: Remaining
      value_template: '{{ ( value | float(0) / 60) | round }}'
      unit: Minutes
    - entity_id: select.huffbot_led_mode
      subtitle: LED Mode
      value_template: |
        {% if value == "1" %}Blinking{% endif %}
        {% if value == "2" %}Always On{% endif %}
        {% if value == "3" %}Disco{% endif %}
    - entity_id: number.huffbot_led_intensity
      subtitle: LED Intensity
      unit: '%'
image: /local/robot_icon_c.svg
show_status: false
show_name: true
```
