### ISSUE TITLE
Transparent Background

### ISSUE THREAD

**Issue by Ringo982** [denysdovhan/vacuum-card#625]
Hello
can u help to create a vacuum card with transparent background?
I've tried with card_mod but it is not working:

type: custom:vacuum-card
card_mod:
  style: |
    ha-card {
      --vc-background: transparent;
      --vc-toolbar-background: transparent;
    }

any help will be appreciated!
Thanks

**Comment by vsnthdev** [comment]
I'm also facing the same issue. With the following code 👇 

```yml
type: custom:vacuum-card
entity: vacuum.deepbot_n10
stats:
  default:
    - entity_id: sensor.deepbot_n10_stats_area
      unit: m²
      subtitle: Area
    - entity_id: sensor.deepbot_n10_stats_time
      unit: min
      subtitle: Time
shortcuts:
  - name: Living room
    service: script.clean_living_room
    icon: mdi:sofa-outline
  - name: Master bedroom
    service: script.clean_master_bedroom
    icon: mdi:bed-king-outline
  - name: Second bedroom
    service: script.clean_second_bedroom
    icon: mdi:lamp-outline
  - name: Kitchen
    service: script.clean_kitchen
    icon: mdi:food-apple-outline
card_mod:
  style: |
    ha-card {
      --vc-background: transparent;
      --vc-toolbar-background: transparent;
    }
```

The card looks like the following 👇 

![Screenshot 2023-11-14 at 5 01 50 PM](https://github.com/denysdovhan/vacuum-card/assets/24322511/e5cb8931-3f58-4ce3-8c08-dd847a9fc485)


Let me check if downgrading `card-mod` or `vacuum-card` makes any difference 🤔

**Comment by vsnthdev** [comment]
Upgrading or downgrading `card-mod` and `vacuum-card` makes no difference.

**Comment by JOHLC** [comment]
Also seeing this
<img width="352" alt="image" src="https://github.com/denysdovhan/vacuum-card/assets/63735432/ff9472ea-5666-4efa-a3fc-54a13c912d65">

**Comment by vsnthdev** [comment]
@JOHLC Which version of card-mod and vacuum card are you using?

Can you please share your vacuum card YAML snippet? I'd like to try this on my setup once to check if something else unrelated is causing this problem 🤔

**Comment by JOHLC** [comment]
> @JOHLC Which version of card-mod and vacuum card are you using?
> 
> Can you please share your vacuum card YAML snippet? I'd like to try this on my setup once to check if something else unrelated is causing this problem 🤔

Latest on both. Please note I am not great with card-mod. Here is my config: 
````
type: custom:vacuum-card
card_mod:
  style: |-
    ha-card {
      --vc-background: transparent;
    }
    :host {
      --ha-card-background: transparent;
      
    }
entity: vacuum.shark_vacuum
compact_view: true
actions:
  pause:
    service: vacuum.stop
    service_data:
      entity_id: vacuum.shark_vacuum
stats:
  default:
    - entity_id: sensor.shark_vacuum_cleaning_time_this_month
      subtitle: Cleaning (month)
      unit: h
    - entity_id: sensor.shark_vacuum_filter_running_time
      subtitle: Filter
      unit: h
    - entity_id: sensor.shark_vacuum_roller_running_time
      subtitle: Roller
      unit: h
    - entity_id: sensor.shark_vacuum_left_brush_running_time
      subtitle: Brush (L)
      unit: h
    - entity_id: sensor.shark_vacuum_right_brush_running_time
      subtitle: Brush (R)
      unit: h
  cleaning:
    - entity_id: sensor.shark_vacuum_cleaning_time_today
      subtitle: Cleaning time today
      unit: h
    - entity_id: sensor.shark_vacuum_running_time_since_maintenance
      subtitle: Runtime since maintenance
      unit: h
shortcuts:
  - name: null
    service: automation.trigger
    service_data:
      entity_id: automation.shark_reload_when_unavailable
    icon: mdi:restart-alert

````
