### ISSUE TITLE
Shortcuts will not display

### ISSUE THREAD

**Issue by inguy24** [denysdovhan/vacuum-card#641]
**Before submitting a bug**

[X ] I updated to the latest version available
[X8 ] I cleared the cache of my browser

**Describe the bug**

shortcuts added in the YAML will not display on the card5

**Steps to reproduce**

1. configured the dashboard YAML as follows:

```
views:
  - title: Home
    icon: mdi:robot-vacuum
    type: panel
    badges: []
    cards:
      - type: custom:vacuum-card
        entity: vacuum.roomba
        shortcuts:
          - name: Clean Living Room
            service: nodered.trigger
            service_data:
              entity_id: button.roomba_node_red_room_trigger
              payload:
                room: living_room
            icon: mdi:sofa

``` 
2. Cleared browser cache
3. Loaded dashboard and shortcut will not display. Also configured pointing to a script as outlined in the github readme, but that configuration also will not work. 

**Expected behavior**
Shortcut should appear with the sofa icon. 

**Screenshots**

**Versions:**

- Release: 2.7.6
- Browser:  chrome, fully kiosk, edge, home assistant app
- HomeAssistant version:

Core
2023.11.2
Supervisor
2023.11.3
Operating System
11.1
Frontend
20231030.2
