### ISSUE TITLE
Add support for Taurus HomeLand Gyro

### ISSUE THREAD

**Issue by Zagur** [denysdovhan/vacuum-card#684]
Hi!

I have been using this [vacuum](https://taurus-home.com/products/homeland-gyro) with the Tuya stand for some time now and the basic functions are working properly.

This time I have been trying to set it up correctly so that it has the best support but I have some doubts.

I attach some pictures of the configuration and some data that I have checked:

Configure entity with localtuya:

![imagen](https://github.com/denysdovhan/vacuum-card/assets/7691406/9bf88327-3984-4d4b-a88c-979e0967b4f0)

![imagen](https://github.com/denysdovhan/vacuum-card/assets/7691406/ad3651fc-098a-4051-b294-091a55228350)

Checking the Tuya API, I have checked all the available dp:

**Standard Instructions**
| CODE | TYPE | VALUES | dp_id |
|--------|--------|--------|--------|
| power | boolean | true, false | 1 |
| power_go | boolean | true, false | 2 |
| mode | Enum | smart, wall_follow, spiral, chargego | 3 |
| direction_control | Enum | backward, turn_left, turn_right, stop | 4 |
| electricity_left | Integer | unit: %, min: 0, max: 100, scale: 0, step: 1 | 6 |
| suction | Enum | strong, normal | 14 | 
| clean_record | String | maxlen:255 | 15 |
| clean_area | Integer | unit: m², min: 0, max: 9999, scale: 0, step: 1| 16 | 
| clean_time | Integer | unit:, min: 0, max: 9999, scale: 0, step: 1 | 17 | 
| fault | bitmap | edge_sweep, middle_sweep, left_wheel, right_wheel, gargabe_box, land_check, collision | 18 |

This is the configuration of the card (by default):

```
type: custom:vacuum-card
entity: vacuum.mayormono
compact_view: false
show_toolbar: true
show_status: true
show_name: true
actions:
  turn_on:
    service: localtuya.set_dp
    data:
      device_id: [device_id]
      dp: 1
      value: true
  turn_off:
    service: localtuya.set_dp
    data:
      device_id: [device_id]
      dp: 1
      value: false
  start:
    service: localtuya.set_dp
    data:
      device_id: [device_id]
      dp: 5
      value: true
  stop:
    service: localtuya.set_dp
    data:
      device_id: [device_id]
      dp: 5
      value: false
  return_to_base:
    service: localtuya.set_dp
    data:
      device_id: [device_id]
      dp: 5
      value: 4
stats:
  cleaning:
    - attribute: clean_time
      unit: minutes
      subtitle: Temps netejant
    - attribute: clean_area
      unit: m²
      subtitle: Àrea netejat
```

From the card, there are options that work well and others that do not. For example, the vacuum is always in the "cleaning" state even though it is in the dock charging.

![imagen](https://github.com/denysdovhan/vacuum-card/assets/7691406/43ed27f2-e574-4f06-add2-c13a360e5e57)

The start button works correctly, but the stop button doesn't seem to do anything. The suction modes work correctly.

Some doubts I have about the whole configuration:

- Is there something wrong configured in the entity of the hoover?
- How does it have to be configured for the chart animation to work correctly?
- DP_ID 15 cannot be configured?
- Is there any way to manage the fault codes?

Regards!
zagur
