### ISSUE TITLE
Card not shown with official Ecovacs integration

### ISSUE THREAD

**Issue by marcolino7** [denysdovhan/vacuum-card#697]
Hi,
I am running HA 2024.2.1 with vacuum-card 2.8.0
Until today I run Ecovacs integration from HACs and all work great for months. After last HA update there is a message to move to new official Ecovacs integration, so I did this change. After that the card is not shown anymore. I event cleared cache, I tried from chrome, firefox and HA Android App with same result, card is not shown.
Here is my configuration:
```
type: vertical-stack
cards:
  - type: custom:vacuum-card
    entity: vacuum.tokio
    image: default
    compact_view: false
    show_name: true
    show_toolbar: true
    show_status: true
    stats:
      default:
        - entity_id: sensor.tokio_life_span_side_brush
          unit: '%'
          subtitle: Side Brush
        - entity_id: sensor.tokio_life_span_brush
          unit: '%'
          subtitle: Main Brush
      cleaning:
        - entity_id: sensor.tokio_stats_area
          unit: m2
          subtitle: Area
        - entity_id: sensor.tokio_stats_total_time
          unit: min
          subtitle: Time
    shortcuts:
      - service: script.deebot_pulisci_ingresso
        icon: mdi:door
      - service: script.deebot_pulisci_cucina
        icon: mdi:fridge
      - service: script.deebot_pulisci_sala
        icon: mdi:table-furniture
      - service: script.deebot_pulisci_salotto
        icon: mdi:sofa
      - service: script.deebot_pulisci_camera
        icon: mdi:bed
```
Any suggestion would be appreciated.

Marco
