### ISSUE TITLE
Card stretches to height of vertical stack

### ISSUE THREAD

**Issue by ssillen** [denysdovhan/vacuum-card#757]
**Before submitting a bug**

[X] I updated to the latest version available
[X] I cleared the cache of my browser

**Describe the bug**

I have the vacuum-card in a vertical stack. The bottom of the card stretches to fit the vertical stack.

**Steps to reproduce**

1. In a dashboard, create a horizontal stack
2. In the horizontal stack, create two vertical stacks
3. In one vertical stack, add the vacuum-card
4. In the second vertical stack, add cards until the total height is more than the vacuum-card
5. The vacuum card stretches to fill the vertical stack

**Expected behavior**
The height of the card is dependent on the contents, not the environment

**Screenshots**
![image](https://github.com/denysdovhan/vacuum-card/assets/83007795/ff7e31ea-0a07-4659-b399-365244a86c94)

**Versions:**

- Release: [e.g. 2.9.3]
- Browser: [chrome]
- HomeAssistant version: [2024.6.1]

**Comment by ssillen** [comment]
A workaround I found is to put the vacuum-card in a separate (nested) vertical stack.
```
- type: vertical-stack
  cards:
    - type: vertical-stack
      cards:
        - type: custom:vacuum-card
          entity: vacuum.wall_e
```
