### ISSUE TITLE
Support DEEBOT X1 OMNI

### ISSUE THREAD

**Issue by JamesDAdams** [denysdovhan/vacuum-card#762]
**Is your feature request related to a problem? Please describe.**
Support the model DEEBOT X1 OMNI

**Describe the solution you'd like**
Support the model DEEBOT X1 OMNI

**Describe alternatives you've considered**
No alternatives for now it's doesn't work.

**Additional context**
With the DEEBOT X1 OMNI i can't get sensors :  

![image](https://github.com/denysdovhan/vacuum-card/assets/20860324/598c59e2-e32e-4707-8df3-8338cc2d3ce6)

**Comment by JamesDAdams** [comment]
> In the code editor, change attribute to entity_id. Set the entity id to the appropriate sensor for the filter e.g. "sensor.walle_filter_lifespan". It should work.

Like this ? It's doesn't work :/

```
stats:
  default:
    - entity_id: sensor.walle_filter_lifespan
      unit: hours
      subtitle: Side brush
```
