### ISSUE TITLE
Card not displayed with vacuum in "Cleaning" state.

### ISSUE THREAD

**Issue by tjonckhe** [denysdovhan/vacuum-card#795]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**

When the robot is in "cleaning" state the vacuum card gets "stuck" and on page refresh the card is not displayed anymore. Any other state filled in via HA Developer tools (also any other random word) gets shown in the card.

See screenshots for the error shown in the Chrome web inspector.

**Steps to reproduce**

1. Go to Lovelace with Vacuum Card
2. Click on "Start cleaning"
3. See error

**Expected behavior**
Card updates state to "cleaning" and remains visible.

**Screenshots**
Web inspector info after "Start cleaning"
![image](https://github.com/user-attachments/assets/e7587160-9a55-4cef-9527-417e621a27db)

Vacuum card after clicking "Start cleaning"
![image](https://github.com/user-attachments/assets/560ed171-5703-4605-9b16-a2686695ef1d)

**Versions:**

- Release: v2.10.1
- Browser: Chrome, HA smartphone app
- HomeAssistant version: 2024.8.2

**Comment by tjonckhe** [comment]
Issue still occurs.

**Comment by tjonckhe** [comment]
Still occurs unfortunately. Tried disabling other cards in HA but issue remained. Anyone here that can support?

**Comment by kade-d** [comment]
@tjonckhe check your cleaning section of your yaml. Mine had an invalid entity id and I saw the same thing

```
cleaning:
    - entity_id: sensor.brush_time ❌ // invalid entity
      value_template: "{{ (value | float(0) / 3600) | round(1) }}"
      subtitle: Main brush
      unit: hours
    - attribute: cleaning_time
      unit: minutes
      subtitle: Cleaning time
```
