### ISSUE TITLE
Bug in value_template

### ISSUE THREAD

**Issue by roumano** [denysdovhan/vacuum-card#899]
**Before submitting a bug**

[x] I updated to the latest version available
[x] I cleared the cache of my browser

**Describe the bug**
i'm using `value_template` in order to round the value, otherwise i get many number after the comma

Via this kind of code : 
```
stats:
  default:
    - entity_id: sensor.q7_max_temps_restant_filtre
      unit: heure
      value_template: "{{ value | float(0) | round(0) }}"
      subtitle: Filtre
    - entity_id: sensor.q7_max_temps_restant_brosse_laterale
      value_template: "{{ value | float(0) | round(0) }}"
      unit: heure
      subtitle: Brosse Latérale
...
```
It's working most of the time, but sometime (can't always reproduce), it's not rounding value 

**Steps to reproduce**

1. Use round value via value_template: 
2. Use the `type: custom:vacuum-card`
3. Sometime, it's will not round anymore value

**Expected behavior**
Value should be always as precise in the value_template

**Screenshots**
* When it's working as expected : 
<img src="https://github.com/user-attachments/assets/ff1d9aef-d121-4125-8605-bcfabfae00f6" width="250">
* When it's NOT working as expected : 
<img src="https://github.com/user-attachments/assets/6955cc3d-a716-4598-839a-39188bd33728" width="250">

**Versions:**

- Release: [v2.10.1]
- Browser: [firefox + home assistant compagnion (android app to connect to HA]
- HomeAssistant version: [2025.01.4]

**Comment by guanaco0403** [comment]
I have the same issue on my side, its verry anoying

**Comment by killi199** [comment]
I use this code and I don't have recognized this Problem using Chrome and the Android App:

```
stats:
  default:
    - entity_id: sensor.roborock_q_revo_verbleibende_filterzeit
      value_template: "{{ value | round(1) }}"
      unit: h
      subtitle: Filter
    - entity_id: sensor.roborock_q_revo_verbleibende_zeit_der_seitenburste
      value_template: "{{ value | round(1) }}"
      unit: h
      subtitle: Seitenbürste
    - entity_id: sensor.roborock_q_revo_verbleibende_zeit_der_hauptburste
      value_template: "{{ value | round(1) }}"
      unit: h
      subtitle: Hauptbürste
    - entity_id: sensor.roborock_q_revo_verbleibende_sensorzeit
      value_template: "{{ value | round(1) }}"
      unit: h
      subtitle: Sensoren
```
