### ISSUE TITLE
Buttons for a manual control

### ISSUE THREAD

**Issue by slydiman** [denysdovhan/vacuum-card#93]
I have created the following buttons for manual control
```
      actions:
        - name: Manual control
          icon: mdi:google-controller
          service: xiaomi_miio.vacuum_remote_control_start
          service_data:
            entity_id: vacuum.miio
        - name: Left turn
          icon: mdi:rotate-left
          service: xiaomi_miio.vacuum_remote_control_move
          service_data:
            entity_id: vacuum.miio
            rotation: 30
            velocity: 0.0
            duration: 1000
        - name: Back
          icon: mdi:arrow-down-bold
          service: xiaomi_miio.vacuum_remote_control_move
          service_data:
            entity_id: vacuum.miio
            velocity: -0.29
            duration: 1000
        - name: Forward
          icon: mdi:arrow-up-bold
          service: xiaomi_miio.vacuum_remote_control_move
          service_data:
            entity_id: vacuum.miio
            velocity: 0.29
            duration: 1000
        - name: Right turn
          icon: mdi:rotate-right
          service: xiaomi_miio.vacuum_remote_control_move
          service_data:
            entity_id: vacuum.miio
            rotation: -30
            velocity: 0.0
            duration: 1000
        - name: Stop manual control
          icon: mdi:google-controller-off
          service: xiaomi_miio.vacuum_remote_control_stop
          service_data:
            entity_id: vacuum.miio
```
But these buttons gone after starting the manual control.
Please integrate them to the UI or add a persistent flag for action buttons.
